add solution for 01-basics 01-counter-button
js-tasks-ru/vue-20201022_sergeiikud pull request #2
Opened 2020-10-26 17:59 UTC by SergiiKudriashov

2020-10-26 20:59 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

Добавляю преподавателя (@ShGKme) для код-ревью, посмотрим что он скажет :)

2020-10-27 00:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Компонент CounterButton
- CounterButton должен иметь числовой входной параметр count со значением 0 по умолчанию
- CounterButton должен рендерить кнопку с текстом count
- CounterButton должен иметь count 0 по умолчанию
- CounterButton должен порождать событие increment с увеличенным на 1 значением по клику
```
```diff
Meetup Page Draft
+ Задача добавлена, но требует ручной проверки
```
```diff
CounterButton
+ Задача добавлена, но требует ручной проверки
```

2020-10-27 10:34 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-27 10:36 UTC, ShGKme requested changes
Задача CounterButton принята.
В задаче MeetupPageDraft требуется избавиться от  XSS и от вызова метода в шаблонах.
В задаче CounterButtonComponent требуется описать модель на параметр и событие, описанное в условии задачи...

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/01-CounterButton/script.js
> +      e.preventDefault();
Вместо `e.preventDefault();` лучше использовать модификатор обработчика событий в шаблоне `@click.prevent=""`.

Но на этой кнопке и не требуется отменять поведение по умолчанию.

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <h5 class="meetup-agenda__title" v-html="getTitleByType(item)"></h5>
v-html выведет значение как html без какого-либо экранирования. Это потенциальный XSS.

Любой пользователь может сделать свой митап с любым заголовком, в том числе использовать там теги или внедрять скрипты. С v-html получится серьёзная дыра в безопасности.

Правильнее использовать обычные выражения `{{ value }}`.

Если так было сделано из-за `<s>` в названии одного из докладов, то это оригинальное название: [https://vueconf.us/schedule/](https://vueconf.us/schedule/). `All you need is <s>love</s> Apollo Client`

Но наличие таких названий не должно приводить к XSS

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <p v-if="isShowSpeakerBlock(item)">
Вызовов методов в шаблоне лучше избегать.
Здесь должно быть простое выражение, либо свойство, либо вычисляемое свойство.

Метод - как обычная функция, будет вызываться каждый раз, когда будет происходить ререндеринг (когда vue встретит вызов метода в шаблоне).
Вычисляемые свойства же будут перевычисляться только тогда, когда изменяются свойства, от которых они зависят. Другими словами можно сказать, что computed - кэшируется.

Да, в этом случае метод очень простой, и это не играет большой роли в плане производительности. Но более декларативным решением будет описать вычисляемое состояние.

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                      v-if="isShowDot(item)"
Аналогично, от вызова метода лучше избавиться

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +            <li v-if="meetup.organizer">
Организатор, место и дата у митапа всегда есть

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.date | formatDate }}</time>
Фильтры deprecated. Они удалены в Vue 3. Лучше уже сейчас ими не пользоваться.
Их можно заменить на вызов метода, или вычисляемое свойство. В будущем можно будет заменить на Pipeline Operator [Stage 2 Proposal](https://github.com/tc39/proposal-pipeline-operator).

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.date | formatDate }}</time>
Значение атрибута `datetime` также требуется привязывать к данным митапа.

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
>    },
Во Vue 3 синтаксис с объектом удалён. Будет поддерживаться только вариант с функцией, возвращающей объект.

2020-10-27 10:36 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
> +console.log('Now you can change meetups right here: "app.id = ${meetupId}"');
В будущем лучше не оставлять никакого вывода в консоль. В задачах с автоматическим тестированием задачником это может считаться за не прошедший тест.

2020-10-27 10:36 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
По условию у кнопки только один входной параметр - `count`.

2020-10-27 10:36 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +      }
`v-model` можно делать не только на `value+input`, но и на любой другой параметр+событие, описав их в свойстве `model`.

2020-10-27 10:36 UTC, ShGKme commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    },
Устанавливать значение по умолчанию в 0 самостоятельно не требуется, оно уже установлено через свойство `default: 0`.

2020-10-27 22:33 UTC, SergiiKudriashov commented on 01-basics/01-CounterButton/script.js
> +      e.preventDefault();
Готово

2020-10-27 22:33 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <h5 class="meetup-agenda__title" v-html="getTitleByType(item)"></h5>
Готово

2020-10-27 22:37 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <p v-if="isShowSpeakerBlock(item)">
Я использовал метода т.к. computed внутри v-if  использовать не выйдет. Пришлось переделать весь массив на computed.
Готово

2020-10-27 22:37 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +                      v-if="isShowDot(item)"
Аналогично, готово

2020-10-27 22:37 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +            <li v-if="meetup.organizer">
Убрал

2020-10-27 22:37 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.date | formatDate }}</time>
Заменил на computed

2020-10-27 22:37 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/index.html
> +              <time datetime="2020-02-31">{{ meetup.date | formatDate }}</time>
Готово

2020-10-27 22:38 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/script.js
>    },
Это мой недосмотр. Блок дата уже был и я не заметил

2020-10-27 22:38 UTC, SergiiKudriashov commented on 01-basics/02-MeetupPageDraft/script.js
> +console.log('Now you can change meetups right here: "app.id = ${meetupId}"');
Убрал

2020-10-27 22:38 UTC, SergiiKudriashov commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +  },
Готово

2020-10-27 22:40 UTC, SergiiKudriashov commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +      }
Готово, этого я не знал. Спасибо

2020-10-27 22:42 UTC, SergiiKudriashov commented on 02-components/01-CounterButtonComponent/CounterButton.js
> +    },
Готово

2020-10-28 03:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2020-10-28 18:08 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/index.html
> +                  <p v-if="isShowSpeakerBlock(item)">
> computed внутри v-if использовать не выйдет

Почему не выйдет?

2020-10-28 18:09 UTC, ShGKme commented on 01-basics/02-MeetupPageDraft/script.js
>    },
Тогда это мой недосмотр :(
Стоило обновить в соответствии с Vue 3

2020-10-28 18:10 UTC, ShGKme approved these changes
Принято 👍

2020-10-28 18:11 UTC, merged